//Save once when we start a new game
IF
	Global("balanceMod_StartSave","GLOBAL",0)
THEN
	RESPONSE #100
    SetGlobal("balanceMod_StartSave","GLOBAL",1)
	SaveGame(1)
	DisplayStringNoName(Myself,@100)
	Continue()
END

//Save on Rest when not using camping supplies (at inns etc)
IF
	PartyRested()
    Global("balanceMod_ManagedRest","GLOBAL",0)
	Global("balanceMod_StartSave","GLOBAL",1)
THEN
	RESPONSE #100
	    SaveGame(1)
    	DisplayStringNoName(Myself,@100)
		Continue()
END
